BookStoreWebsite/src/com/bookstore/entity/BookOrder.java
package com.bookstore.entity;
// Generated Aug 4, 2020 1:02:16 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@Table(name = "book_order", catalog = "bookstoredb")
@NamedQueries({
		@NamedQuery(name = "BookOrder.findAll", query = "select bo from BookOrder bo" + " order by bo.orderDate desc"),
		@NamedQuery(name = "BookOrder.countAll", query = "select count(*) from BookOrder"),
		@NamedQuery(name = "BookOrder.findByCustomer", query = "select bo from BookOrder bo"
				+ " where bo.customer.customerId =:customerId order by bo.orderDate desc"),
		@NamedQuery(name = "BookOrder.findByIdAndCustomer", query = "select bo from BookOrder bo"
				+ " where  bo.orderId=:orderId and    bo.customer.customerId =:customerId "),

})

public class BookOrder implements java.io.Serializable {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BookOrder other = (BookOrder) obj;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		return true;
	}

	private Integer orderId;
	private Customer customer;
	private Date orderDate;
	private String addressLine1;
	private String addressLine2;
	private String firstname;
	private String lastname;
	private String phone;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String paymentMethod;

	private float total;
	private float subtotal;
	private float shippingFee;
	private float tax;
	private String status;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public BookOrder() {
	}

	public BookOrder(Customer customer, Date orderDate, String shippingAddress, String recipientName,
			String recipientPhone, String paymentMethod, float total, String status) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.addressLine1 = shippingAddress;
		this.firstname = recipientName;
		this.phone = recipientPhone;
		this.paymentMethod = paymentMethod;
		this.total = total;
		this.status = status;
	}

	public BookOrder(Customer customer, Date orderDate, String shippingAddress, String recipientName,
			String recipientPhone, String paymentMethod, float total, String status, Set<OrderDetail> orderDetails) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.addressLine1 = shippingAddress;
		this.firstname = recipientName;
		this.phone = recipientPhone;
		this.paymentMethod = paymentMethod;
		this.total = total;
		this.status = status;
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "r_address_line1", nullable = false)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "r_address_line2", nullable = false)
	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "r_lastname", nullable = false)
	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "r_phone", nullable = false)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "r_city", nullable = false)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "r_state", nullable = false)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "r_zipcode", nullable = false)
	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "r_country", nullable = false)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "subtotal", nullable = false, precision = 255, scale = 0)
	public float getSubtotal() {
		return subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "shipping_fee", nullable = false, precision = 255, scale = 0)
	public float getShippingFee() {
		return shippingFee;
	}

	public void setShippingFee(float shippingFee) {
		this.shippingFee = shippingFee;
	}

	@Column(name = "tax", nullable = false, precision = 255, scale = 0)
	public float getTax() {
		return tax;
	}

	public void setTax(float tax) {
		this.tax = tax;
	}

	@Column(name = "r_firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

//	@Column(name = "recipient_phone", nullable = false)
//	public String getRecipientPhone() {
//		return this.phone;
//	}
//
//	public void setRecipientPhone(String recipientPhone) {
//		this.phone = recipientPhone;
//	}

	@Column(name = "payment_method", nullable = false)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "total", nullable = false, precision = 255, scale = 0)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bookOrder", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Transient
	public int getBookCopies() {
		int total = 0;
		for (OrderDetail orderDetail : orderDetails) {
			total += orderDetail.getQuantity();
		}
		return total;
	}
	
	@Transient
	public String getCountryName() {
		return new Locale("",this.country).getDisplayCountry();
	}


}

BookStoreWebsite/src/com/bookstore/entity/Customer.java
package com.bookstore.entity;
// Generated Jul 21, 2020 10:09:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "bookstoredb")
@NamedQueries({ @NamedQuery(name = "Customer.findAll", query = "select c from Customer c order by c.registerDate desc"),
		@NamedQuery(name = "Customer.countAll", query = "select count(*) from Customer c "),
		@NamedQuery(name = "Customer.findByEmail", query = "select c from Customer c where c.email = :email"),
		@NamedQuery(name = "Customer.checkLogin", query = "select c from Customer c where c.email=:email and c.password=:password")

})
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String email;
	private String firstname;
	private String lastname;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	private Date registerDate;
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

	public Customer() {
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city,
			String state,String country, String phone, String zipcode, String password, Date registerDate) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.addressLine1 = address1;
		this.addressLine2 = address2;
		this.city = city;
		this.state=state;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.registerDate = registerDate;
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city,
			String state,String country, String phone, String zipcode, String password, Date registerDate, Set<Review> reviews,
			Set<BookOrder> bookOrders) {
		this(email, firstname, lastname, address1, address2, city,state, country, phone, zipcode, password, registerDate);
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	@Transient
	public String getFullname() {
		return this.firstname+" "+this.lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "address_line1", nullable = false)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String address1) {
		this.addressLine1 = address1;
	}
	
	@Column(name = "address_line2", nullable = false)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String address2) {
		this.addressLine2 = address2;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "state", nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	@Transient
	public String getCountryName() {
		return new Locale("",this.country).getDisplayCountry();
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", nullable = false)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}
	

}

BookStoreWebsite/src/com/bookstore/controller/admin/book/CreateBookServlet.java
package com.bookstore.controller.admin.book;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;


@WebServlet("/admin/create_book")
@MultipartConfig(
		fileSizeThreshold = 1024*10, //10kb
		maxFileSize = 1024*300,
		maxRequestSize = 1024*1024   //1mb
		)
public class CreateBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
   
    public CreateBookServlet() {
        super();
    }

	

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		BookServices bookServices= new BookServices(request, response);
		bookServices.createBook();
		
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/book/DeleteBookServlet.java
package com.bookstore.controller.admin.book;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;

@WebServlet("/admin/delete_book")
public class DeleteBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
    public DeleteBookServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		BookServices bookServices= new BookServices(request, response);
		bookServices.deleteBook();
	}

	
	

}

BookStoreWebsite/src/com/bookstore/controller/admin/book/EditBookServlet.java
package com.bookstore.controller.admin.book;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;


@WebServlet("/admin/edit_book")
public class EditBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		BookServices bookServices=new BookServices(request, response);
		bookServices.editBook();
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/book/ListBookServlet.java
package com.bookstore.controller.admin.book;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;


@WebServlet("/admin/list_books")
public class ListBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		BookServices bookServices= new BookServices(request, response);
		bookServices.listBooks();
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/book/NewBookServlet.java
package com.bookstore.controller.admin.book;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;


@WebServlet("/admin/new_book")
public class NewBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		BookServices bookServices=new BookServices(request, response);
		bookServices.showBookNewForm();
	}

}

BookStoreWebsite/WebContent/admin/add_book_form.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Add Book to Order</title>
</head>
<body>
	<div align="center">
		<h2>Add Book to Order ID : ${order.orderId }</h2>

		<form action="add_book_to_order" method="post">
			<table>
				<tr>
					<td>Select a Book :</td>
					<td><select name="bookId">
							<c:forEach items="${listBook}" varStatus="status" var="book">
								<option value="${book.bookId }">${book.title }-
									${book.author }</option>

							</c:forEach>


					</select></td>



				</tr>
				<tr>
					<td>&nbsp; &nbsp;</td>
				</tr>
				<tr>
					<td>Number of Copies :</td>
					<td><select name="quantity">
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>

					</select></td>
				</tr>
				<tr>
					<td>&nbsp; &nbsp;</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
					<input type="submit" value="Add">
					&nbsp; &nbsp;
					 <input
						type="button" value="Cancel" onclick="javascript:self.close();"></td>

				</tr>



			</table>



		</form>

	</div>


</body>
</html>

BookStoreWebsite/WebContent/admin/customer_list.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Manage Customers</title>
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css">
<script type="text/javascript"
	src="<%=request.getContextPath()%>/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript"
	src="<%=request.getContextPath()%>/js/jquery.validate.min.js"></script>

</head>
<body>
	<jsp:directive.include file="header.jsp" />
	<div align="center">
		<h2 class="pageheading">Customers Manegement</h2>
		<h3>
			<a href="new_customer">Create new Customer</a>
		</h3>
	</div>
	
	<c:if test="${message!=null}">
	
	<div align="center">

		<h4 class="message" > ${message} </h4>
	</div>
	</c:if>

	<div align="center">
		<table border="1" cellpadding="5">
			<tr>
				<th>Index</th>
				<th>ID</th>
				<th>E-mail</th>
				<th>Frist Name</th>
				<th>Last Name</th>
				<th>City</th>
				<th>Country</th>
				<th>registered Date</th>
				<th>Actions</th>


			</tr>

			<c:forEach var="customer" items="${listCustomer}" varStatus="status">
				<tr>
					<td>${status.index+1}</td>
					<td>${customer.customerId}</td>
					<td>${customer.email}</td>
					<td>${customer.firstname}</td>
					<td>${customer.lastname}</td>
					<td>${customer.city}</td>
					<td>${customer.countryName}</td>
					<td><fmt:formatDate pattern="MM/dd/yyyy" value="${customer.registerDate}"/></td>
					
					<td>
					<a href="edit_customer?id=${customer.customerId}">Edit</a>&nbsp
					<a href="javascript:void(0);" class="deleteLink" id="${customer.customerId}">Detele</a>
					</td>


				</tr>

			</c:forEach>


		</table>
	</div>



	<jsp:directive.include file="footer.jsp" />
	<script type="text/javascript">
	$(document).ready(function(){
		$(".deleteLink").each(function(){
			$(this).on("click",function(){
				customerId=$(this).attr("id");
				if(confirm('Are you sure to wanna delete the customer with ID '+customerId+ ' ?')){
					window.location='delete_customer?id='+customerId;
				}
			});
		});
	});
	
	
	</script>
</body>
</html>

BookStoreWebsite/WebContent/admin/index.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>BookStore Admin</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
</head>
<body>
	<jsp:directive.include file="header.jsp" />
	<div align="center">
		<h2 class="pageheading">Adminitrative Dashboard</h2>
	</div>

	<div align="center">
		<hr width="60%" />

		<h2 class="pageheading">Quick action:</h2>
		<b> <a href="new_book">New Book</a> &nbsp; <a href="user_form.jsp">New
				User</a>&nbsp; <a href="category_form.jsp">New Category</a>&nbsp; <a
			href="new_customer">New Customer</a>
		</b>

	</div>
	<div align="center">
		<hr width="60%" />
		<h2 class="pageheading">Recent sales:</h2>

		<table border="1">

			<tr>
				<th>Oder ID</th>
				<th>Ordered By</th>
				<th>Book Copies</th>
				<th>Total</th>
				<th>Payment Method</th>
				<th>Status</th>
				<th>Order Date</th>
			</tr>
			<c:forEach items="${listMostRecentSales}" var="order"
				varStatus="status">
				<tr>
					<td><a href="view_order?id=${order.orderId}">${order.orderId }</a></td>
					<td>${order.customer.fullname }</td>
					<td>${order.bookCopies }</td>
					<td><fmt:setLocale value="en_US" /> <fmt:formatNumber
							value="${order.total}" type="currency" /></td>
					<td>${order.paymentMethod }</td>
					<td>${order.status }</td>
					<td>${order.orderDate }</td>



				</tr>

			</c:forEach>

		</table>
	</div>
	<div align="center">
		<hr width="60%" />
		<h2 class="pageheading">Recent Reviews:</h2>
		<table border="1">

			<tr>
				<th>Book </th>
				<th>Rating</th>
				<th>Headline</th>
				<th>Customer</th>
				<th>Review On</th>
				
			</tr>
			<c:forEach items="${listReview}" var="review"
				varStatus="status">
				<tr>
					<td>${review.book.title }</td>
					<td>${review.rating }</td>
					<td><a href="edit_review?id=${review.reviewId}">${review.headline }</a></td>
					<td>${review.customer.fullname }</td>
					<td>${review.reviewTime }</td>
				</tr>

			</c:forEach>
			

		</table>
	</div>
	<div align="center">
		<hr width="60%" />
		<h2 class="pageheading">Statistics:</h2>
		<b>Total Users:</b><i>${totalUsers }</i>&nbsp;&nbsp;&nbsp;
		<b>Total Books:</b><i>${totalBooks }</i>&nbsp;&nbsp;&nbsp;
		<b>Total Customers:</b><i>${totalCustomers }</i>&nbsp;&nbsp;&nbsp;
		<b>Total Reviews:</b><i>${totalReviews }</i>&nbsp;&nbsp;&nbsp;
		<b>Total Orders:</b><i>${totalOrders }</i>&nbsp;&nbsp;&nbsp;
		<hr width="60%" />
	</div>

	<jsp:directive.include file="footer.jsp" />
</body>
</html>

BookStoreWebsite/WebContent/admin/order_list.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Manages Orders</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
<script type="text/javascript"
	src="<%=request.getContextPath()%>/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript"
	src="<%=request.getContextPath()%>/js/jquery.validate.min.js"></script>
</head>
<body>
	<jsp:directive.include file="header.jsp" />
	<div align="center">
		<h2 class="pageheading">Book Orders Management</h2>
	</div>

	<c:if test="${message!=null}">

		<div align="center">

			<h4 class="message">${message}</h4>
		</div>
	</c:if>

	<div align="center">
		<table border="1" cellpadding="5">
			<tr>
				<th>Index</th>
				<th>Order ID</th>
				<th>Ordered By</th>
				<th>Book Copies</th>
				<th>Total</th>
				<th>Payment Method</th>
				<th>Status</th>
				<th>Order Date</th>
				<th>Actions</th>


			</tr>

			<c:forEach var="order" items="${listOrder}" varStatus="status">
				<tr>
					<td>${status.index+1}</td>
					<td>${order.orderId}</td>
					<td>${order.customer.fullname}</td>
					<td>${order.bookCopies}</td>
					<td><fmt:setLocale value="en_US" /> <fmt:formatNumber
							value="${order.total}" type="currency" /></td>
					<td>${order.paymentMethod}</td>
					<td>${order.status}</td>
					<td>${order.orderDate}</td>
					
					<td>
					<a href="view_order?id=${order.orderId}">Details
					&nbsp
					<a href="edit_order?id=${order.orderId}">Edit</a>
					&nbsp
						<a href="javascript:void(0);" class="deleteLink"
						id="${order.orderId}">Detele</a></td>


				</tr>

			</c:forEach>


		</table>
	</div>



	<jsp:directive.include file="footer.jsp" />
	<script type="text/javascript">
	$(document).ready(function(){
		$(".deleteLink").each(function(){
			$(this).on("click",function(){
				orderId=$(this).attr("id");
				if(confirm('Are you sure to wanna delete the order with ID '+orderId+ ' ?')){
					window.location='delete_order?id='+orderId;
				}
			});
		});
	});
	
	</script>
</body>
</html>