BookStoreWebsite/src/com/bookstore/entity/Book.java
package com.bookstore.entity;
// Generated Jun 8, 2020 9:01:50 AM by Hibernate Tools 5.2.12.Final

import java.util.Base64;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bookstoredb")
@NamedQueries({ @NamedQuery(name = "Book.findAll", query = "select b from Book b "),
		@NamedQuery(name = "Book.findByTitle", query = "select b from Book b where b.title = :title"),
		@NamedQuery(name = "Book.countAll", query = "select count(*) from Book b "),
		@NamedQuery(name = "Book.findByCategory", query = "select b from Book b join Category c on b.category.categoryId = c.categoryId "
				+ "and c.categoryId =:catId"),
		@NamedQuery(name = "Book.listNew", query = "select b from Book b order by b.publishDate desc "),
		@NamedQuery(name = "Book.search", query = "select b from Book b where b.title like '%' || :keyword || '%'"
				+ "or b.author like '%' || :keyword  ||'%'" + "or b.description  like '%' || :keyword  ||'%'"),

})
public class Book implements java.io.Serializable {

	private Integer bookId;
	private Category category;
	private String title;
	private String author;
	private String description;
	private String isbn;
	private byte[] image;
	private String base64Image;
	private float price;
	private Date publishDate;
	private Date lastUpdateTime;
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Book() {
	}

	public Book(Integer bookId) {
		super();
		this.bookId = bookId;
	}

	public Book(Category category, String title, String author, String description, String isbn, byte[] image,
			float price, Date publishDate, Date lastUpdateTime) {
		this.category = category;
		this.title = title;
		this.author = author;
		this.description = description;
		this.isbn = isbn;
		this.image = image;
		this.price = price;
		this.publishDate = publishDate;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Book(Category category, String title, String author, String description, String isbn, byte[] image,
			float price, Date publishDate, Date lastUpdateTime, Set<Review> reviews, Set<OrderDetail> orderDetails) {
		this.category = category;
		this.title = title;
		this.author = author;
		this.description = description;
		this.isbn = isbn;
		this.image = image;
		this.price = price;
		this.publishDate = publishDate;
		this.lastUpdateTime = lastUpdateTime;
		this.reviews = reviews;
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "book_id", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", nullable = false)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isbn", nullable = false)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "book")
	public Set<Review> getReviews() {
		TreeSet<Review> sortedReviews = new TreeSet<Review>(new Comparator<Review>() {

			@Override
			public int compare(Review review1, Review review2) {
				return review2.getReviewTime().compareTo(review1.getReviewTime());
			}

		});

		sortedReviews.addAll(reviews);
		return sortedReviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Transient
	public String getBase64Image() {
		this.base64Image = Base64.getEncoder().encodeToString(this.image);
		return this.base64Image;
	}

	@Transient
	public float getAverageRating() {
		float averageRating = 0.0f;
		float sum = 0.0f;
		if (reviews.isEmpty()) {
			return 0.0f;
		}
		for (Review review : reviews) {
			sum += review.getRating();

		}
		averageRating = sum / reviews.size();
		return averageRating;
	}

	@Transient
	public String getRatingStars() {
		float averageRating = getAverageRating();
		return getRatingString(averageRating);
	}

	@Transient
	public String getRatingString(float averageRating) {
		String result = "";
		int numberOfStarsOn = (int) averageRating;
		for (int i = 1; i <= numberOfStarsOn; i++) {
			result += "on,";
		}
		int next = numberOfStarsOn + 1;
		if (averageRating > numberOfStarsOn) {
			result += "half,";
			next++;
		}
		for (int j = next; j <= 5; j++) {
			result += "off,";
		}
		return result.substring(0, result.length() - 1);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookId == null) ? 0 : bookId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Book other = (Book) obj;
		if (bookId == null) {
			if (other.bookId != null)
				return false;
		} else if (!bookId.equals(other.bookId))
			return false;
		return true;
	}

	@Transient
	public void setBase64Image(String base64Image) {
		this.base64Image = base64Image;

	}

}

BookStoreWebsite/src/com/bookstore/entity/Customer.java
package com.bookstore.entity;
// Generated Jul 21, 2020 10:09:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "bookstoredb")
@NamedQueries({ @NamedQuery(name = "Customer.findAll", query = "select c from Customer c order by c.registerDate desc"),
		@NamedQuery(name = "Customer.countAll", query = "select count(*) from Customer c "),
		@NamedQuery(name = "Customer.findByEmail", query = "select c from Customer c where c.email = :email"),
		@NamedQuery(name = "Customer.checkLogin", query = "select c from Customer c where c.email=:email and c.password=:password")

})
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String email;
	private String firstname;
	private String lastname;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	private Date registerDate;
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

	public Customer() {
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city,
			String state,String country, String phone, String zipcode, String password, Date registerDate) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.addressLine1 = address1;
		this.addressLine2 = address2;
		this.city = city;
		this.state=state;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.registerDate = registerDate;
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city,
			String state,String country, String phone, String zipcode, String password, Date registerDate, Set<Review> reviews,
			Set<BookOrder> bookOrders) {
		this(email, firstname, lastname, address1, address2, city,state, country, phone, zipcode, password, registerDate);
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	@Transient
	public String getFullname() {
		return this.firstname+" "+this.lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "address_line1", nullable = false)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String address1) {
		this.addressLine1 = address1;
	}
	
	@Column(name = "address_line2", nullable = false)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String address2) {
		this.addressLine2 = address2;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "state", nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	@Transient
	public String getCountryName() {
		return new Locale("",this.country).getDisplayCountry();
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", nullable = false)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}
	

}

BookStoreWebsite/src/com/bookstore/entity/Review.java
package com.bookstore.entity;
// Generated Jul 25, 2020 5:21:43 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


@Entity
@Table(name = "review", catalog = "bookstoredb")
@NamedQueries({
	@NamedQuery(name = "Review.listAll",query = "select r from Review r order by r.reviewTime desc"),
	@NamedQuery(name = "Review.countAll", query = "select count(r) from Review r"),

	@NamedQuery(name = "Review.findByCustomerAndBook",query = "select r from Review r "
			+ "where r.customer.customerId =:customerId "
			+ "and r.book.bookId =:bookId"),
	@NamedQuery(name = "Review.mostFavoredBooks",query = "select r.book,"
			+ " count(r.book.bookId) as ReviewCount,"
			+ " avg(r.rating) as AvgRating from Review r "
			+ " group by r.book.bookId having avg(r.rating)>=4.0 order by "
			+ "ReviewCount desc, AvgRating desc")
	
	 
})
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Book book;
	private Customer customer;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Review() {
	}

	public Review(Book book, Customer customer, int rating, String headline, String comment, Date reviewTime) {
		this.book = book;
		this.customer = customer;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}
	@Transient
	public String getStars() {
		String result="";
		int numberOfStarsOn= (int) rating;
		for(int i=1;i<=numberOfStarsOn;i++) {
			result+="on,";
		}
		for(int j=numberOfStarsOn+1;j<=5;j++) {
			result+="off,";
		}
		return result.substring(0,result.length()-1);
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/review/DeleteReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/delete_review")
public class DeleteReviewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
    
    public DeleteReviewServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		ReviewServices reviewServices= new ReviewServices(request, response);
		reviewServices.deleteReview();
	}

}

BookStoreWebsite/WebContent/frontend/book_detail.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>${book.title}</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
	<script type="text/javascript"

	src="<%=request.getContextPath()%>/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript"
	src="<%=request.getContextPath()%>/js/jquery.validate.min.js"></script>
</head>
<body>
	<jsp:directive.include file="header.jsp" />

	<div class="center1">
		<table class="book">
			<tr>
				<td colspan="3" align="left">

					<p id="book-title">${book.title } </p>
					 by <span id="author"> ${book.author }</span>

				</td>
			</tr>

			<tr>
				<td rowspan="2"><img class="book-large"
					src="data:image/jpg;base64,${book.base64Image }"  /></td>
				<td valign="top" align="left">
				<c:forTokens items="${book.ratingStars}" delims="," var="star">
				<c:if test="${star eq 'on'}">
				<img src="<%=request.getContextPath()%>/images/rating_on.png">
				</c:if>
				<c:if test="${star eq 'off'}">
				<img src="<%=request.getContextPath()%>/images/rating_off.png">
				</c:if>
				<c:if test="${star eq 'half'}">
				<img src="<%=request.getContextPath()%>/images/rating_half.png">
				</c:if>
				
				</c:forTokens>
				
				<a href="#reviews">${fn:length(book.reviews) } Reviews</a>
				</td>
				<td valign="top" rowspan="2" width="20%"><h2>$${book.price }</h2> <br />
					<button id="buttonAddToCart">Add to cart</button>
				</td>

			</tr>
			<tr>
				<td id="description">${book.description }</td>
			</tr>
			
			<tr>
			<td> &nbsp; </td>
			</tr>
			<tr>
			<td>
			<h2><a id="reviews">Customer Reviews </a></h2>
			</td>
			<td colspan="2" align="center">
			<button id="buttonWriteReview">Write a Customer Review</button>
			
			</td>
			
			</tr>
			<td colspan="3" align="left">
			<table>
			<c:forEach items="${book.reviews}" var="review">
			<tr>
			<td>
			<c:forTokens items="${review.stars}" delims="," var="star">
				<c:if test="${star eq 'on'}">
				<img src="<%=request.getContextPath()%>/images/rating_on.png">
				</c:if>
				<c:if test="${star eq 'off'}">
				<img src="<%=request.getContextPath()%>/images/rating_off.png">
				</c:if>
				
				</c:forTokens>
			-<b>${review.headline }</b>
			</td>
			
			
			</tr>
			<tr>
			<td>
			by <i> ${review.customer.fullname } </i> on ${review.reviewTime}
			</td>
			
			</tr>
			
			<tr> <td> <i>${review.comment } </i>    </td>   </tr>
			<tr> <td> &nbsp; </td>  </tr>
			
			
			
			</c:forEach>
			
			
			
			</table>
			
			</td>
			<tr>
			
			
			
			</tr>
		</table>



	</div>
	<jsp:directive.include file="footer.jsp" />
	<script type="text/javascript">
	$(document).ready(function() {
		
		$("#buttonWriteReview").click(function() {
			window.location='write_review?book_id=' +${book.bookId};
			
		});
		
		$("#buttonAddToCart").click(function() {
			window.location='add_to_cart?book_id=' +${book.bookId};
			
		});
	
	
	});
</script>
</body>
</html>

BookStoreWebsite/WebContent/frontend/book_rating.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

BookStoreWebsite/WebContent/frontend/books_list_by_category.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Books in <c:out value="${category.name}" /> - Online
	Books Store
</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
</head>
<body>
	<jsp:directive.include file="header.jsp" />

	<div class="center">
		<h2>${category.name}</h2>


	</div>
	<div class="book_group">
		<c:forEach items="${listBooks}" var="book">
			<div class="book">
				<div>
					<a href="view_book?id=${book.bookId}"> <img class="book-small"
						src="data:image/jpg;base64,${book.base64Image }" />
					</a>
				</div>
				<div>
					<a href="view_book?id=${book.bookId}"> <b>${book.title } </b>
					</a>
				</div>
				<div>
				
				<c:forTokens items="${book.ratingStars}" delims="," var="star">
				<c:if test="${star eq 'on'}">
				<img src="<%=request.getContextPath()%>/images/rating_on.png">
				</c:if>
				<c:if test="${star eq 'off'}">
				<img src="<%=request.getContextPath()%>/images/rating_off.png">
				</c:if>
				<c:if test="${star eq 'half'}">
				<img src="<%=request.getContextPath()%>/images/rating_half.png">
				</c:if>
				
				</c:forTokens>
				
				</div>
				<div>
					<i>by ${book.author} </i>
				</div>
				<div>
					<b>$${book.price}</b>
				</div>
			</div>


		</c:forEach>
	</div>
	<jsp:directive.include file="footer.jsp" />
</body>
</html>

BookStoreWebsite/WebContent/frontend/customer_profile.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Customer Profile</title>
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/style.css">
</head>
<body>
<jsp:directive.include file="header.jsp" />
<div align="center">
<br>

		<h2> Welcome, ${loggedCustomer.fullname}</h2>
		<br>
	
<table>
<tr>
<td> <b>E-mail Address : </b>  </td>
<td>${loggedCustomer.email } </td>
</tr>

<tr>
<td> <b>First Name : </b>  </td>
<td>${loggedCustomer.firstname } </td>
</tr>

<tr>
<td> <b>Last Name : </b>  </td>
<td>${loggedCustomer.lastname } </td>
</tr>

<tr>
<td> <b>Phone Number : </b>  </td>
<td>${loggedCustomer.phone } </td>
</tr>
<tr>
<td> <b>Address Line 1 : </b>  </td>
<td>${loggedCustomer.addressLine1 } </td>
</tr>

<tr>
<td> <b>Address Line 2: </b>  </td>
<td>${loggedCustomer.addressLine2 } </td>
</tr>
<tr>
<td> <b>City : </b>  </td>
<td>${loggedCustomer.city } </td>
</tr>

<tr>
<td> <b>State : </b>  </td>
<td>${loggedCustomer.state } </td>
</tr>

<tr>
<td> <b>Zip Code : </b>  </td>
<td>${loggedCustomer.zipcode } </td>
</tr>
<tr>
<td> <b>Country : </b>  </td>
<td>${loggedCustomer.countryName } </td>
</tr>
<tr><td>  &nbsp;</td>   </tr>
<tr>
<td colspan="2" align="center"><b><a href="edit_profile">Edit My Profile </b></a></td>
</tr>
</table>
</div>
<jsp:directive.include file="footer.jsp" />
</body>
</html>

BookStoreWebsite/WebContent/frontend/footer.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
</head>
<body>
<div align="center" style="clear: both;">
<h4>Coppyright (C) 2020 by TranVietSon Books</h4>
<a href="about">About Us</a>
<a href="contact">Contact Us</a>
<a href="policy">Privacy Policy</a>
<a href="shipping">Shipping & Delivery</a>

</div>
</body>
</html>

BookStoreWebsite/WebContent/frontend/header.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">
</head>
<body>
	<div class="center">
		<div>
		<a href="${pageContext.request.contextPath }">
			<img alt=""
				
				src="<%=request.getContextPath()%>/images/logo1.png">
				</a>
		</div>
		<div>
			<form action="search" method="get">


				<input type="text" name="keyword" size="50"> <input
					type="submit" value="Search">
			
			&nbsp;&nbsp;&nbsp;&nbsp;
			<c:if test="${loggedCustomer==null}">
			 <a href="login">Sign in</a> |
			  <a href="register">Register </a>|
			</c:if>
			<c:if test="${loggedCustomer!=null}">
			 <a href="view_profile">Welcome, ${loggedCustomer.fullname}</a> |
			  <a href="view_orders">My Orders </a>|
			   <a href="logout">Logout </a>|
			</c:if>
			
			   <a href="view_cart">Cart</a>
				</form>
		</div>
		<div>&nbsp;</div>

		<div>

			<c:forEach var="category" items="${listCategory }" varStatus="status">
				<a href="view_category?id=${category.categoryId}"> <font
					size="+1"> <b><c:out value="${category.name}" /> </b></font>
				</a>
				<c:if test="${not status.last}">
				&nbsp; | &nbsp;
				</c:if>

			</c:forEach>
		</div>


	</div>

</body>
</html>